In [1]:
import torch

In [2]:
t1 = torch.tensor([1,1,1])

In [3]:
t1.unsqueeze(dim = 0)

tensor([[1, 1, 1]])

In [4]:
t1.unsqueeze(dim = 1)

tensor([[1],
        [1],
        [1]])

In [5]:
print(t1.shape)
print(len(t1.shape))
print((t1.unsqueeze(dim = 0).shape))
print(len(t1.unsqueeze(dim = 0).shape))
print((t1.unsqueeze(dim = 1).shape))

torch.Size([3])
1
torch.Size([1, 3])
2
torch.Size([3, 1])


In [6]:
import torch

t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [8]:
torch.cat((t1,t2,t3),dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
torch.stack((t1,t2,t3),dim=0)

In [ ]:
torch.cat((t1.unsqueeze(0),t2.unsqueeze(0),t3.unsqueeze(0)),dim=0)

In [ ]:
import torch
n1 = torch.zeros(3,5,5)
n2 = torch.zeros(3,5,5)
n3 = torch.zeros(3,5,5)


In [ ]:
n = torch.stack(
    (n1,n2,n3)
    ,dim=0
)

In [ ]:
print(n)

In [ ]:
n = torch.stack(
    (n1,n2,n3)
    ,dim=0
).shape

In [ ]:
print(n)

In [ ]:

t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)


In [ ]:
torch.stack(
    (t1,t2,t3)
    ,dim=0
).shape

In [ ]:
import torch
t1 = torch.zeros(1,3,5,5)
t2 = torch.zeros(1,3,5,5)
t3 = torch.zeros(1,3,5,5)
torch.cat(
    (t1,t2,t3)
    ,dim=0
)

In [ ]:
t1 = torch.zeros(1,3,5,5)

In [ ]:
t1

In [ ]:
n1 = torch.zeros(5,5)

In [ ]:
print(n1)

In [ ]:
n1 = torch.zeros(2,5,5)

In [ ]:
n1

In [ ]:
n1 = torch.zeros(2,2,5,5)

In [ ]:
n1

In [ ]:
n1 = torch.zeros(0,1,2,2)

In [ ]:
n1